config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :player
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def index
    @players = Player.all
  end
  
  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)

    @player.save
    redirect_to player_index_path
  end
  
  def edit
    @player = Player.find(params[:id])
  end
  
  def update
    @player = Player.find(params[:id])
    @player.update(player_params)
    
    redirect_to player_index_path
  end
  
  def show
    @player = Player.find(params[:id])
  end
  
  def destroy
    @player = Player.find(params[:id])
    @player.destroy
 
    redirect_to player_index_path
  end

  private
  def player_params
    params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<%= link_to  "Player", player_index_path %>

app/views/player/edit.html.erb
<%= link_to  "Back", player_index_path %>

<%= form_for @player, url: player_path do |form| %>
<p>
  <%= form.label :nickName %><br>
  <%= form.text_field :nickname %>
</p>
<p>
  <%= form.label :rank %><br>
  <%= form.text_field :rank %>
</p>
<p>
  <%= form.label :charisma %><br>
  <%= form.text_field :charisma %>
</p>
<p>
  <%= form.label :wisdom %><br>
  <%= form.text_field :wisdom %>
</p>

<p>
  <%= form.submit %>
</p>
<% end %>

app/views/player/index.html.erb
<%= link_to  "Back", root_path %>
<%= link_to  "NEW", new_player_path %>

<table>
    <tr>
      <th>Nick Name</th>
      <th>Rank</th>
      <th>Charisma</th>
      <th>Wisdom</th>
    </tr>
   
    <% @players.each do |p| %>
      <tr>
        <td><%= link_to p.nickname, player_path(p) %></td>
        <td><%= p.rank %></td>
        <td><%= p.charisma %></td>
        <td><%= p.wisdom %></td>
        <td><%= link_to 'Edit', edit_player_path(p) %></td>
        <td><%= link_to 'Delete', player_path(p), method: :delete, data:{confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </table>

app/views/player/new.html.erb
<%= link_to  "Back", player_index_path %>

<%= form_for @player, url: player_index_path do |form| %>
<p>
  <%= form.label :nickName %><br>
  <%= form.text_field :nickname %>
</p>
<p>
  <%= form.label :rank %><br>
  <%= form.text_field :rank %>
</p>
<p>
  <%= form.label :charisma %><br>
  <%= form.text_field :charisma %>
</p>
<p>
  <%= form.label :wisdom %><br>
  <%= form.text_field :wisdom %>
</p>

<p>
  <%= form.submit %>
</p>
<% end %>

app/views/player/show.html.erb
<%= link_to  "Back", player_index_path %>
<p>
<strong>Name:</strong>
<%= @player.nickname %>
</p>
<p>
<strong>Rank:</strong>
<%= @player.rank %>
</p>
<p>
<strong>Charisma:</strong>
<%= @player.charisma %>
</p>
<p>
<strong>Wisdom:</strong>
<%= @player.wisdom %>
</p>